# Generated by Django 5.0.2 on 2024-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
