# Generated by Django 5.0.2 on 2024-04-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0007_rooms_play_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_started',
            new_name='room_started_time',
        ),
    ]
