# Generated by Django 5.0.2 on 2024-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0009_updatedusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_started_time',
            field=models.DateTimeField(null=True),
        ),
    ]
