# Generated by Django 5.0.2 on 2024-05-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0010_alter_rooms_room_started_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='minutes_for_player',
            field=models.CharField(default='1:00', max_length=5),
        ),
    ]
