# Generated by Django 5.0.2 on 2024-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0011_rooms_minutes_for_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='wasted',
            field=models.BooleanField(default=False),
        ),
    ]
